apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
      annotations: # <--- ADD THIS BLOCK
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000" # Your app listens on port 3000
        prometheus.io/path: "/metrics" # Default path, adjust if your app uses a different one
    spec:
      containers:
      - name: backend-app
        image: 311042608592.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "100m"
