apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on (e.g., for external access)
      targetPort: 3000 # The port your container is listening on (EXPOSE 3000 in Dockerfile)
      name: http # <--- ADDED: This name is crucial for ServiceMonitor discovery
  type: LoadBalancer # Creates an AWS Classic Load Balancer to expose your service
