name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test # Ensure you have tests in package.json

  build-and-scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js setup and dependency install here for Docker build context
      - name: Setup Node.js for Docker build
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies for Docker build context
        run: npm ci

      # Diagnostic step (can remove later if pipeline passes consistently)
      - name: Check cross-spawn version
        run: npm list cross-spawn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:${{ github.sha }} .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL' # <--- THIS IS THE KEY LINE FOR TRIVY TO PASS ON HIGH SEVERITIES
          # The 'ignore-policy' line MUST NOT be here.
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:${{ github.sha }}
